"""
config.py — Secure Continuous Monitoring System v4
Priority: .env file, environment variables, safe defaults.
"""

import os, secrets
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
ENV_FILE = BASE_DIR / ".env"

def _load_env_file():
    if not ENV_FILE.exists(): return
    with open(ENV_FILE) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line: continue
            key, _, val = line.partition("=")
            key = key.strip(); val = val.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = val

_load_env_file()

def _e(key, default=None):
    return os.environ.get(key, default)

# ── Server ────────────────────────────────────────────────────────────────────
SERVER_HOST = _e("SERVER_HOST", "0.0.0.0")
SERVER_PORT = int(_e("SERVER_PORT", 5000))


# Use localhost as the default so self-hosted agents work
_ingest_host = "localhost" if SERVER_HOST in ("0.0.0.0", "", "::") else SERVER_HOST
SERVER_URL = _e("SERVER_URL", f"http://{_ingest_host}:{SERVER_PORT}/ingest")

# ── Database ──────────────────────────────────────────────────────────────────
DB_CONFIG = {
    "host":     _e("DB_HOST",     "localhost"),
    "database": _e("DB_NAME",     "scms"),
    "user":     _e("DB_USER",     "postgres"),
    "password": _e("DB_PASSWORD", ""),
    "port":     int(_e("DB_PORT", 5432)),
}

# ── Auth / API ────────────────────────────────────────────────────────────────
API_KEY    = _e("API_KEY")
SECRET_KEY = _e("SECRET_KEY")
RATE_LIMIT = int(_e("RATE_LIMIT_PER_MINUTE", 300))

# ── Data-at-rest encryption ───────────────────────────────────────────────────
# 64 hex chars (32 bytes = 256 bits). Generated by install.py.
FIELD_ENCRYPTION_KEY = _e("FIELD_ENCRYPTION_KEY", "")

# ── Log sources ───────────────────────────────────────────────────────────────
_default_logs = [
    "/var/log/auth.log", "/var/log/syslog", "/var/log/kern.log",
    "/var/log/dpkg.log", "/var/log/boot.log", "/var/log/audit/audit.log",
    "/root/.bash_history",
]
_env_logs = _e("LOG_FILES", "")
TEXT_LOG_FILES = [p for p in _env_logs.split(",") if p] if _env_logs else _default_logs

_env_journals = _e("JOURNAL_UNITS", "")
JOURNAL_UNITS = [u for u in _env_journals.split(",") if u] if _env_journals else [
    "sshd", "sudo", "systemd", "user"
]

# ── TLS ───────────────────────────────────────────────────────────────────────
TLS_CERT = _e("TLS_CERT_PATH", "")
TLS_KEY  = _e("TLS_KEY_PATH",  "")

# ── SMTP ──────────────────────────────────────────────────────────────────────
SMTP_HOST     = _e("SMTP_HOST", "")
SMTP_PORT     = int(_e("SMTP_PORT", 587))
SMTP_USER     = _e("SMTP_USER", "")
SMTP_PASSWORD = _e("SMTP_PASSWORD", "")
SMTP_FROM     = _e("SMTP_FROM", "")
SMTP_TO       = _e("SMTP_TO", "")

# ── Feature flags ─────────────────────────────────────────────────────────────
ENABLE_RATE_LIMIT = _e("ENABLE_RATE_LIMIT", "true").lower() != "false"
ENABLE_CSP        = _e("ENABLE_CSP",        "true").lower() != "false"

# ── Safe fallbacks ────────────────────────────────────────────────────────────
import logging as _logging
if not API_KEY:
    _logging.warning("API_KEY missing — ephemeral key generated. Run install.py.")
    API_KEY = secrets.token_hex(32)
if not SECRET_KEY:
    SECRET_KEY = secrets.token_hex(32)
if not FIELD_ENCRYPTION_KEY:
    _logging.warning("FIELD_ENCRYPTION_KEY missing — data-at-rest encryption DISABLED.")
