#!/usr/bin/env python3
"""
install.py — Secure Continuous Monitoring System
First-run installer.  Creates the database, tables, admin user, and .env file.
Run once after cloning: sudo python3 install.py
"""

import os
import sys
import re
import secrets
import getpass
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
ENV_FILE = BASE_DIR / ".env"

G = "\033[92m"; R = "\033[91m"; Y = "\033[93m"; C = "\033[96m"
B = "\033[1m"; X = "\033[0m"


def banner():
    print(f"""
{C}{B}
  ╔══════════════════════════════════════════════════════╗
  ║   SCMS — Secure Continuous Monitoring System v4      ║
  ║   ICS/SCADA SIEM — First-Run Installer               ║
  ╚══════════════════════════════════════════════════════╝
{X}""")


def _prompt(label: str, default: str = "", secret: bool = False) -> str:
    hint = f" [{default}]" if default and not secret else ""
    try:
        if secret:
            val = getpass.getpass(f"  {label}: ")
        else:
            val = input(f"  {label}{hint}: ").strip()
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(0)
    return val or default


def collect_config() -> dict:
    print(f"\n{B}── Database Configuration ────────────────────────────────{X}")
    cfg = {
        "DB_HOST":     _prompt("PostgreSQL host", "localhost"),
        "DB_PORT":     _prompt("PostgreSQL port", "5432"),
        "DB_USER":     _prompt("PostgreSQL user", "postgres"),
        "DB_PASSWORD": _prompt("PostgreSQL password", secret=True),
        "DB_NAME":     "",
    }
    while True:
        name = _prompt("Database name", "scms")
        if re.match(r'^[a-zA-Z0-9_\-]{1,64}$', name):
            cfg["DB_NAME"] = name
            break
        print(f"  {R}Invalid database name — use letters, digits, _ or -{X}")

    print(f"\n{B}── Server Configuration ──────────────────────────────────{X}")
    cfg["SERVER_HOST"] = _prompt("Server bind address", "0.0.0.0")
    cfg["SERVER_PORT"] = _prompt("Server port", "5000")

    print(f"\n{B}── SMTP Alert Configuration (optional) ───────────────────{X}")
    cfg["SMTP_HOST"]     = _prompt("SMTP host (leave blank to skip)", "")
    cfg["SMTP_PORT"]     = _prompt("SMTP port", "587") if cfg["SMTP_HOST"] else "587"
    cfg["SMTP_USER"]     = _prompt("SMTP user", "") if cfg["SMTP_HOST"] else ""
    cfg["SMTP_PASSWORD"] = _prompt("SMTP password", secret=True) if cfg["SMTP_HOST"] else ""
    cfg["SMTP_FROM"]     = _prompt("From address", "") if cfg["SMTP_HOST"] else ""
    cfg["SMTP_TO"]       = _prompt("Alert recipient(s)", "") if cfg["SMTP_HOST"] else ""

    return cfg


def generate_secrets(cfg: dict) -> dict:
    cfg["SECRET_KEY"]           = secrets.token_hex(32)
    cfg["API_KEY"]              = secrets.token_hex(32)
    cfg["FIELD_ENCRYPTION_KEY"] = secrets.token_hex(32)
    return cfg


def write_env(cfg: dict):
    lines = [
        "# SCMS environment — generated by install.py",
        "# Treat this file as a secret — do not commit to version control.",
        "",
        "# Database",
        f'DB_HOST={cfg["DB_HOST"]}',
        f'DB_PORT={cfg["DB_PORT"]}',
        f'DB_USER={cfg["DB_USER"]}',
        f'DB_PASSWORD={cfg["DB_PASSWORD"]}',
        f'DB_NAME={cfg["DB_NAME"]}',
        "",
        "# Server",
        f'SERVER_HOST={cfg["SERVER_HOST"]}',
        f'SERVER_PORT={cfg["SERVER_PORT"]}',
        "",
        "# Secrets (DO NOT SHARE)",
        f'SECRET_KEY={cfg["SECRET_KEY"]}',
        f'API_KEY={cfg["API_KEY"]}',
        f'FIELD_ENCRYPTION_KEY={cfg["FIELD_ENCRYPTION_KEY"]}',
    ]
    if cfg.get("SMTP_HOST"):
        lines += [
            "",
            "# SMTP",
            f'SMTP_HOST={cfg["SMTP_HOST"]}',
            f'SMTP_PORT={cfg["SMTP_PORT"]}',
            f'SMTP_USER={cfg["SMTP_USER"]}',
            f'SMTP_PASSWORD={cfg["SMTP_PASSWORD"]}',
            f'SMTP_FROM={cfg["SMTP_FROM"]}',
            f'SMTP_TO={cfg["SMTP_TO"]}',
        ]
    ENV_FILE.write_text("\n".join(lines) + "\n")
    os.chmod(ENV_FILE, 0o600)
    print(f"\n  {G}✔  .env written → {ENV_FILE}{X}")


def setup_database(cfg: dict) -> bool:
    try:
        import psycopg2
    except ImportError:
        print(f"  {R}psycopg2 not installed — pip install psycopg2-binary{X}")
        return False

    # Create database if needed
    try:
        conn = psycopg2.connect(
            host=cfg["DB_HOST"], port=int(cfg["DB_PORT"]),
            user=cfg["DB_USER"], password=cfg["DB_PASSWORD"],
            database="postgres",
        )
        conn.autocommit = True
        with conn.cursor() as cur:
            cur.execute("SELECT 1 FROM pg_database WHERE datname=%s", (cfg["DB_NAME"],))
            if not cur.fetchone():
                cur.execute(f'CREATE DATABASE "{cfg["DB_NAME"]}"')
                print(f"  {G}✔  Database '{cfg['DB_NAME']}' created{X}")
            else:
                print(f"  {Y}⚠  Database '{cfg['DB_NAME']}' already exists{X}")
        conn.close()
    except Exception as exc:
        print(f"  {R}✘  Cannot connect to PostgreSQL: {exc}{X}")
        return False

    # Create tables
    try:
        # Set env so setup_db can read it
        for k, v in cfg.items():
            os.environ[f"DB_{k.split('_',1)[-1]}" if k.startswith("DB_") else k] = v
        os.environ["DB_NAME"] = cfg["DB_NAME"]
        os.environ["DB_HOST"] = cfg["DB_HOST"]
        os.environ["DB_PORT"] = cfg["DB_PORT"]
        os.environ["DB_USER"] = cfg["DB_USER"]
        os.environ["DB_PASSWORD"] = cfg["DB_PASSWORD"]

        import setup_db
        ok = setup_db.create_tables()
        if ok:
            print(f"  {G}✔  Tables and indexes ready{X}")
        return ok
    except Exception as exc:
        print(f"  {R}✘  Table creation failed: {exc}{X}")
        return False


def create_admin_user(cfg: dict) -> bool:
    print(f"\n{B}── Admin User ─────────────────────────────────────────────{X}")
    username = _prompt("Admin username", "admin")
    while True:
        password = _prompt("Admin password (min 12 chars)", secret=True)
        if len(password) >= 12:
            break
        print(f"  {R}Password must be at least 12 characters{X}")
    confirm = _prompt("Confirm password", secret=True)
    if password != confirm:
        print(f"  {R}Passwords do not match — user not created{X}")
        return False

    try:
        # Bootstrap env before importing auth
        for k, v in cfg.items():
            os.environ[k] = v
        from server.auth import create_user
        ok, msg = create_user(username, password, role="admin")
        if ok:
            print(f"  {G}✔  Admin user '{username}' created{X}")
        else:
            print(f"  {Y}⚠  {msg}{X}")
        return ok or "already exists" in msg
    except Exception as exc:
        print(f"  {R}User creation failed: {exc}{X}")
        return False


def print_summary(cfg: dict):
    port = cfg.get("SERVER_PORT", "5000")
    print(f"""
{G}{B}  ╔══════════════════════════════════════════════════════╗
  ║   Installation complete!                              ║
  ╚══════════════════════════════════════════════════════╝{X}

  {B}Start SCMS:{X}
    python3 scms.py start

  {B}Dashboard:{X}
    http://localhost:{port}

  {B}Keys stored in:{X} .env  (chmod 600 — keep secret)

  {Y}Tip: Run behind nginx with TLS for production.
  Set SESSION_COOKIE_SECURE=True in app.py when TLS is active.{X}
""")


def main():
    banner()

    if ENV_FILE.exists():
        ans = input(f"  {Y}.env already exists — overwrite? [y/N]: {X}").strip().lower()
        if ans != "y":
            print("  Aborting."); sys.exit(0)

    cfg = collect_config()
    cfg = generate_secrets(cfg)
    write_env(cfg)

    print(f"\n{B}── Database Setup ────────────────────────────────────────{X}")
    db_ok = setup_database(cfg)
    if not db_ok:
        print(f"\n  {Y}⚠  Skipping user creation — fix DB connection and re-run{X}")
        sys.exit(1)

    create_admin_user(cfg)
    print_summary(cfg)


if __name__ == "__main__":
    main()
